Repository WilliamKarolDiCioccio/fl_nodes, pull requests merged in 2025-02, with the labels that each got.

#29 Remove Tuple dependency in favor of Dart Records
  example/pubspec.lock
  lib/src/core/controllers/node_editor/clipboard.dart
  lib/src/core/controllers/node_editor/core.dart
  lib/src/core/controllers/node_editor/runner.dart
  lib/src/core/models/entities.dart
  lib/src/core/utils/spatial_hash_grid.dart
  lib/src/widgets/node.dart
  lib/src/widgets/node_editor.dart
  lib/src/widgets/node_editor_render_object.dart
  pubspec.yaml
Labels: Status: Completed, Type: Enhancement, dependencies

#33 Enhanced UI improvements
  example/macos/Podfile.lock
  example/pubspec.lock
  lib/src/core/models/styles.dart
  lib/src/widgets/node.dart
  lib/src/widgets/node_editor.dart
  lib/src/widgets/node_editor_render_object.dart
Labels: Status: In Progress, Type: Enhancement

#39 Fix/input
  example/lib/main.dart
  example/pubspec.lock
  lib/src/widgets/node.dart
  lib/src/widgets/node_editor_data_layer.dart
Labels: Type: Bug, Priority: Critical, Status: Accepted, Type: Enhancement
