Repository WilliamKarolDiCioccio/fl_nodes, pull requests merged in 2025-01, with the labels that each got.

#13 Add Trackpad Input
  example/.gitignore
  example/macos/Podfile.lock
  example/macos/Runner.xcodeproj/project.pbxproj
  example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/macos/Runner.xcworkspace/contents.xcworkspacedata
  example/macos/Runner/AppDelegate.swift
  example/pubspec.lock
  lib/src/utils/improved_listener.dart
  lib/src/widgets/node_editor.dart
Labels: Status: Accepted

#20 Add undo/redo history feature
  lib/src/core/controllers/node_editor.dart
  lib/src/core/controllers/node_editor_config.dart
  lib/src/core/controllers/node_editor_event_bus.dart
  lib/src/core/controllers/node_editor_events.dart
  lib/src/core/models/entities.dart
  lib/src/core/utils/constants.dart
  lib/src/core/utils/stack.dart
  lib/src/widgets/debug_info.dart
  lib/src/widgets/hierarchy.dart
  lib/src/widgets/node.dart
  lib/src/widgets/node_editor.dart
  lib/src/widgets/node_editor_render_object.dart
Labels: Type: Feature

#21 Add graph runner feature
  example/lib/main.dart
  lib/src/core/controllers/node_editor/core.dart
  lib/src/core/controllers/node_editor/runner.dart
  lib/src/core/models/entities.dart
  lib/src/widgets/node.dart
  lib/src/widgets/node_editor_render_object.dart
Labels: Status: In Progress, Type: Feature
